//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VMServiceReference.IVMService")]
    public interface IVMService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVMService/SetDataBaseName", ReplyAction="http://tempuri.org/IVMService/SetDataBaseNameResponse")]
        System.Threading.Tasks.Task SetDataBaseNameAsync(string dbName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVMService/SetServerName", ReplyAction="http://tempuri.org/IVMService/SetServerNameResponse")]
        System.Threading.Tasks.Task SetServerNameAsync(string serverName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVMService/Connect", ReplyAction="http://tempuri.org/IVMService/ConnectResponse")]
        System.Threading.Tasks.Task<bool> ConnectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IVMServiceChannel : VMServiceReference.IVMService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class VMServiceClient : System.ServiceModel.ClientBase<VMServiceReference.IVMService>, VMServiceReference.IVMService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VMServiceClient() : 
                base(VMServiceClient.GetDefaultBinding(), VMServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVMService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VMServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VMServiceClient.GetBindingForEndpoint(endpointConfiguration), VMServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VMServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VMServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VMServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VMServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task SetDataBaseNameAsync(string dbName)
        {
            return base.Channel.SetDataBaseNameAsync(dbName);
        }
        
        public System.Threading.Tasks.Task SetServerNameAsync(string serverName)
        {
            return base.Channel.SetServerNameAsync(serverName);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectAsync()
        {
            return base.Channel.ConnectAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVMService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVMService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/VMService/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VMServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVMService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VMServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVMService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVMService,
        }
    }
}
